apiVersion: v1
kind: Service
metadata:
  name: llm-inference-service
  namespace: default
spec:
  selector:
    app: llm-inference
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
